### ISSUE TITLE
Syntax 

### ISSUE THREAD

**Issue by malys** [Marvin700/Windows_Optimisation_Pack#30]
Hi,
I have detected an error l. 149

`"else { IF($WindowsVersion -eq "Microsoft Windows 10 Home" -Or $WindowsVersion -eq "Microsoft Windows 10 Pro" -Or $WindowsVersion -eq "Microsoft Windows 11 Enterprise") {"`

"Windows 11" instead of "Windows 10".

Moreover, there are different versions of Windows Enterprise (normal and N for EU citizens). It could be interesting to change:
 $WindowsVersion -eq "Microsoft Windows xx Enterprise" to $WindowsVersion  -clike "Microsoft Windows 11 Enterprise"

or add "Microsoft Windows xx Entreprise N"

Thanks for your script.

Bye

**Comment by Marvin700** [comment]
Thank you for suggestion for improvement.
I try to implement this at the weekend :)

The Syntax Error is fixed and Reuploaded to Version 1.8

**Comment by Marvin700** [comment]
Implemented for new Version. :)

**Comment by malys** [comment]
Perfect, it works fine. Thx
