### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by RobertWork** [Marvin700/Windows_Optimisation_Pack#31]
does it affect any graphic issues

**Comment by Marvin700** [comment]
What do you exactly mean ?

**Comment by RobertWork** [comment]
I meant when maybe editing videos, audio editing or maybe video games, Does
it boost graphics performance or is it the same...

**Comment by RobertWork** [comment]
I meant does it affect video editing, audio or gaming... as the description
says it lowers cpu and ram usage, may that affect the something

**Comment by Marvin700** [comment]
I Always test the optimizer To my daily use PC before uploading. 
The only Thing the Script deletes, are Things like one Drive or docker ( cause Subsystem for Linux).
The Script create always a system restore point for safety, that you can Go Back, if you are unhappy with the result.
If you find a function you want To exclude, i can Help you with that. 

If you are still unsecure about using the Script, i can offer you a explanation via discord :)

Hope i could Help you with that answer ^^
