### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by Keerigan45** [Marvin700/Windows_Optimisation_Pack#43]
Hello, is it possible to revert back the admin right toa user. Cuz i want said user to enable windows defender cloud extension. Have a great day !

**Comment by Keerigan45** [comment]
or if i can just revert back the whole admin thing created.

**Comment by Marvin700** [comment]
Hi,
sry for the late reply.


You can Adjust the Settings with the Tool ooShutup
![image](https://github.com/user-attachments/assets/b696e946-4e67-4363-b062-2ecf295f1bd8)

optional:
config File:
S014	+	# Disable reporting of malware infection information (Category: Microsoft Defender and Microsoft SpyNet)
https://www.oo-software.com/de/shutup10
