### ISSUE TITLE
Toolbar language icon cannot be displayed

### ISSUE THREAD

**Issue by kennytatf** [Marvin700/Windows_Optimisation_Pack#45]
Toolbar language icon cannot be displayed

**Comment by Marvin700** [comment]
Hello,
What do you mean by that?

**Comment by kennytatf** [comment]
Language bar missing from taskbar
and I cant ctrl++ space to change lang

**Comment by kennytatf** [comment]
how can i fix it

**Comment by Marvin700** [comment]
@kennytatf 

I cannot replicate your issue ...
Windows 10 and Windows 11 with my new config.

Do you have a 2nd language installed ?
Only then u can can see language icon in the taskbar

**Comment by Marvin700** [comment]
Which WIndows / WIndows Version do you use ?

Which Windows_Optimisation_Pack version ?
![image](https://github.com/user-attachments/assets/dec26fd5-4e11-4bf6-be8a-5d7ff14b190a)

**Comment by Marvin700** [comment]
no answer
